# Generated by Django 5.2.1 on 2025-06-02 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NombreTaller',
            fields=[
                ('id_nombre_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'nombre_taller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id_programa_educativo', models.AutoField(primary_key=True, serialize=False)),
                ('programa_educativo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'programa_educativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id_situacion', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'situacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id_tipo_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_ingreso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estado')),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.pais')),
            ],
            options={
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('curp', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=60)),
                ('email_personal', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('iems_procedencia', models.CharField(max_length=255)),
                ('generacion', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('discapacidad', models.BooleanField()),
                ('nombre_discapacidad', models.CharField(max_length=255)),
                ('motivo_situacion', models.CharField(max_length=255)),
                ('beca', models.BooleanField()),
                ('tipo_beca', models.CharField(max_length=255)),
                ('creditos', models.FloatField()),
                ('derecho_servicio_social', models.BooleanField()),
                ('fecha_nac', models.DateField()),
                ('sexo', models.BooleanField()),
                ('hablante_indigena', models.BooleanField()),
                ('nombre_lengua', models.CharField(max_length=255)),
                ('promedio', models.FloatField()),
                ('id_estatus', models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estatus')),
                ('id_pro_edu', models.ForeignKey(db_column='id_programa_educativo', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.programaeducativo')),
                ('id_situacion', models.ForeignKey(db_column='id_situacion', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.situacion')),
                ('id_tipo_ingreso', models.ForeignKey(db_column='id_tipo_ingreso', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.tipoingreso')),
            ],
            options={
                'db_table': 'estudiante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id_egresado', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('telefono_casa', models.CharField(max_length=10)),
                ('red_social', models.CharField(max_length=255)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'egresado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=35)),
                ('acreditado', models.BooleanField()),
                ('certificacion', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estudiante', models.ForeignKey(db_column='estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'idioma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovilidadAcad',
            fields=[
                ('id_movilidad_acad', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('acreditado', models.BooleanField()),
                ('beca', models.BooleanField()),
                ('nombre_beca', models.CharField(max_length=255)),
                ('tipo_vinculacion', models.BooleanField()),
                ('huesped', models.BooleanField()),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.ciudad')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'vinculacion_acad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PracticaProf',
            fields=[
                ('id_practica_prof', models.AutoField(primary_key=True, serialize=False)),
                ('num_practica', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('empresa', models.CharField(max_length=255)),
                ('telefon_empresa', models.CharField(max_length=15)),
                ('contratado', models.BooleanField()),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'practica_prof',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_proyecto', models.BooleanField()),
                ('clase_proyecto', models.CharField(max_length=40)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('beneficiarios', models.CharField(max_length=255)),
                ('evidencias', models.BinaryField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estadoservicio')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'servicio_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_taller', models.BooleanField()),
                ('representante', models.BooleanField()),
                ('selectivo', models.BooleanField()),
                ('acreditado', models.BooleanField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('club', models.CharField(max_length=255)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
                ('id_nombre_taller', models.ForeignKey(db_column='id_nombre_taller', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.nombretaller')),
            ],
            options={
                'db_table': 'taller',
                'managed': True,
            },
        ),
    ]
