# Generated by Django 5.2.1 on 2025-06-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='egresado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estadoservicio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movilidadacad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nombretaller',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AlterModelOptions(
            name='practicaprof',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programaeducativo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviciosocial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='situacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipoingreso',
            options={},
        ),
        migrations.AddField(
            model_name='practicaprof',
            name='practica_internacional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistorialEstatus',
            fields=[
                ('id_historial_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estatus', models.DateField()),
                ('id_estatus', models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estatus')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'historial_estatus',
            },
        ),
        migrations.CreateModel(
            name='HistorialSituacion',
            fields=[
                ('id_historial_situacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_situacion', models.DateField()),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
                ('id_situacion', models.ForeignKey(db_column='id_situacion', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.situacion')),
            ],
            options={
                'db_table': 'historial_situacion',
            },
        ),
    ]
