# Generated by Django 5.2.1 on 2025-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_ciudad_options_alter_egresado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='titulado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
