# Generated by Django 5.2.1 on 2025-06-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_estudiante_titulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicaprof',
            name='practica_internacional',
        ),
    ]
