# Generated by Django 5.2.1 on 2025-06-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_remove_practicaprof_practica_internacional'),
        ('profesores', '0006_rename_id_perfil_seii_perfilseii_id_perfil_seii_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesarrolloAcademico',
            fields=[
                ('id_desarrollo_academico', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_tutoria', models.CharField()),
                ('tipo_tutoria', models.BooleanField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
        ),
    ]
