# Generated by Django 5.2.1 on 2025-06-10 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0002_alter_ciudad_options_alter_egresado_options_and_more'),
        ('usuarios', '0003_alter_contrasena_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoSubcategoria',
            fields=[
                ('id_evento_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'evento_subcategoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaseProyecto',
            fields=[
                ('id_fase_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('fase', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fase_proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id_grado_academico', models.AutoField(primary_key=True, serialize=False)),
                ('grado_academico', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'grado_academico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradoAsesoria',
            fields=[
                ('id_grado_asesoria', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grado_asesoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id_investigacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('objeto_estudio', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('numero_edicion', models.CharField(max_length=255)),
                ('lugar_publicacion', models.CharField(max_length=255)),
                ('nombre_institucion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'investigacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('etapa', models.CharField(max_length=30)),
                ('financiamiento', models.BooleanField()),
                ('resultados', models.TextField()),
            ],
            options={
                'db_table': 'proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id_tipo_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_capacitacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstancia',
            fields=[
                ('id_tipo_estancia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estancia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_estancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoProfesor',
            fields=[
                ('id_tipo_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_profesor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_profesor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id_tipo_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_proyecto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id_estancia', models.AutoField(primary_key=True, serialize=False)),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.ciudad')),
                ('id_tipo_estancia', models.ForeignKey(db_column='id_tipo_estancia', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.tipoestancia')),
            ],
            options={
                'db_table': 'estancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_asesoria', models.BooleanField()),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('recursos', models.BooleanField()),
                ('id_fases_proyecto', models.ForeignKey(db_column='id_fase_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.faseproyecto')),
                ('id_grado_asesoria', models.ForeignKey(db_column='id_grado_asesoria', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.gradoasesoria')),
            ],
            options={
                'db_table': 'asesoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_pat', models.CharField(max_length=40)),
                ('apellido_mat', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('sexo', models.BooleanField()),
                ('jefe_departamento', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
                ('id_grado_academico', models.ForeignKey(db_column='id_grado_academico', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.gradoacademico')),
                ('id_programa_educativo', models.ForeignKey(db_column='id_programa_educativo', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.programaeducativo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
                ('id_tipo_profesor', models.ForeignKey(db_column='id_tipo_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.tipoprofesor')),
            ],
            options={
                'db_table': 'profesor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id_excursion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_excursion', models.BooleanField()),
                ('destino', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('evidencias', models.CharField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.asignatura')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'excursion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_estudios', models.AutoField(primary_key=True, serialize=False)),
                ('grado_actual', models.CharField(max_length=50)),
                ('grado_estudiando', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('nombre_institucion', models.CharField(max_length=255)),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'estudios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaInterna',
            fields=[
                ('id_asesoria_interna', models.AutoField(primary_key=True, serialize=False)),
                ('id_asesoria', models.ForeignKey(db_column='id_asesoria', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.asesoria')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'asesoria_interna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaExterna',
            fields=[
                ('id_asesoria_externa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asesorado', models.CharField(max_length=255)),
                ('id_asesoria', models.ForeignKey(db_column='id_asesoria', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.asesoria')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'asesoria_externa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActividadInactivo',
            fields=[
                ('id_actividad_inactivo', models.AutoField(primary_key=True, serialize=False)),
                ('carta_autorizacion', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('carta_aceptacion', models.CharField(max_length=255)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('carta_incorporacion', models.CharField(max_length=255)),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'actividad_inactivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfesorEstancia',
            fields=[
                ('id_profesor_estancia', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('objetivo', models.TextField()),
                ('resultados', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_estancia', models.ForeignKey(db_column='id_estancia', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.estancia')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'profesor_estancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfesorInvestigacion',
            fields=[
                ('id_profesor_investigacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_investigacion', models.ForeignKey(db_column='id_investigacion', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.investigacion')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'profesor_investigacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfesorProyecto',
            fields=[
                ('id_profesor_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.proyecto')),
            ],
            options={
                'db_table': 'profesor_proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=255)),
                ('sede', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
                ('id_tipo_capacitacion', models.ForeignKey(db_column='id_tipo_capacitacion', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.tipocapacitacion')),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id_evento_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_evento_subcategoria', models.ForeignKey(db_column='id_evento_subcategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.eventosubcategoria')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
                ('id_tipo_evento', models.ForeignKey(db_column='id_tipo_evento', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.tipoevento')),
            ],
            options={
                'db_table': 'evento_acad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='investigacion',
            name='tipo_producto',
            field=models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.tipoproducto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.ForeignKey(db_column='id_tipo_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.tipoproyecto'),
        ),
    ]
