# Generated by Django 5.2.1 on 2025-06-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_ciudad_options_alter_egresado_options_and_more'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id_tutoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tutoria', models.BooleanField()),
                ('carta_asignacion', models.TextField()),
                ('motivo_tutoria', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.estudiante')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'tutoria',
                'managed': True,
            },
        ),
    ]
