# Generated by Django 5.2.1 on 2025-06-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_tutoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProdep',
            fields=[
                ('id_perfil_prodep', models.AutoField(primary_key=True, serialize=False)),
                ('pertenece_prodep', models.BooleanField()),
                ('vigencia_prodep', models.CharField()),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'perfil_prodep',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilSeii',
            fields=[
                ('id_perfil_Seii', models.AutoField(primary_key=True, serialize=False)),
                ('pertenece_Seii', models.BooleanField()),
                ('nivel_Seii', models.CharField()),
                ('vigencia_Seii', models.CharField()),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'perfil_Seii',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilSnii',
            fields=[
                ('id_perfil_snii', models.AutoField(primary_key=True, serialize=False)),
                ('pertenece_snii', models.BooleanField()),
                ('nivel_snii', models.CharField()),
                ('vigencia_snii', models.CharField()),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.profesor')),
            ],
            options={
                'db_table': 'perfil_snii',
                'managed': True,
            },
        ),
    ]
