# Generated by Django 5.2.1 on 2025-06-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_perfilprodep_perfilseii_perfilsnii'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelInvestigador',
            fields=[
                ('id_nivel_investigador', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_investigador', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='perfilseii',
            name='nivel_Seii',
            field=models.ForeignKey(db_column='id_nivel_investigador', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.nivelinvestigador'),
        ),
        migrations.AlterField(
            model_name='perfilsnii',
            name='nivel_snii',
            field=models.ForeignKey(db_column='id_nivel_investigador', on_delete=django.db.models.deletion.DO_NOTHING, to='profesores.nivelinvestigador'),
        ),
    ]
