# Generated by Django 5.2.1 on 2025-06-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0004_nivelinvestigador_alter_perfilseii_nivel_seii_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilseii',
            old_name='nivel_Seii',
            new_name='id_nivel',
        ),
        migrations.RenameField(
            model_name='perfilsnii',
            old_name='nivel_snii',
            new_name='id_nivel',
        ),
    ]
