# Generated by Django 5.2.1 on 2025-06-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0005_rename_nivel_seii_perfilseii_id_nivel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilseii',
            old_name='id_perfil_Seii',
            new_name='id_perfil_seii',
        ),
        migrations.RenameField(
            model_name='perfilseii',
            old_name='pertenece_Seii',
            new_name='pertenece_seii',
        ),
        migrations.RenameField(
            model_name='perfilseii',
            old_name='vigencia_Seii',
            new_name='vigencia_seii',
        ),
    ]
