# Generated by Django 5.2.1 on 2025-06-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('id_contrasena', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contrasena',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipoUsuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('apellido_pat_usuario', models.CharField(max_length=30)),
                ('apellido_mat_usuario', models.CharField(max_length=30)),
                ('correo_usuario', models.CharField(max_length=40)),
                ('id_contrasena', models.ForeignKey(db_column='id_contrasena', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.contrasena')),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
