# Generated by Django 5.2.1 on 2025-06-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido_mat_usuario',
            new_name='apellido_mat',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido_pat_usuario',
            new_name='apellido_pat',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo_usuario',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nombre',
        ),
    ]
