# Generated by Django 5.2.1 on 2025-06-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_apellido_mat_usuario_usuario_apellido_mat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrasena',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='tipo_usuario',
        ),
    ]
