# Generated by Django 5.2.1 on 2025-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_contrasena_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
