# Generated by Django 5.2.1 on 2025-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
